# Generated by Django 4.0.1 on 2022-11-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('car_model', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
