# Generated by Django 4.0.1 on 2022-11-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_contact_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.BooleanField(default=False),
        ),
    ]
