# Generated by Django 4.0.1 on 2022-11-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_contact_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='booking',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='gis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='google',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='trip_advisor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='vlru',
            field=models.BooleanField(default=True),
        ),
    ]
