# Generated by Django 4.0.1 on 2022-11-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_first_name_contact_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='star1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='star2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='star3',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='star4',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='star5',
            field=models.BooleanField(default=True),
        ),
    ]
